import snapshot from "./releases.snapshot.json";
import type { Release } from "./releases";

/**
 * The last known good release list.
 *
 * Generated by `scripts/sync-releases.mjs`. Do not edit by hand: run
 * `pnpm sync` after publishing a release.
 *
 * This exists so the site still renders when the GitHub API is unreachable or
 * rate-limited during a build. It is a fallback, not the data source. When the
 * API answers, `getReleases` uses the live list instead.
 */
export const releaseSnapshot: Release[] = snapshot as Release[];